name:                agda2java
version:             0.1.0.0
github:              "githubuser/agda2java"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/agda2java#readme>

dependencies:
- base >= 4.7 && < 5
- text
- Agda >= 2.6.2.1 && < 2.6.3
- language-java >= 0.2.9
- deepseq >= 1.4.5
- ghc
- filepath >= 1.4 && < 2
- containers
- directory

library:
  source-dirs: src

executables:
  agda2java-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - agda2java

tests:
  agda2java-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - agda2java
    
default-extensions:
  - BlockArguments
  - DeriveAnyClass
  - DeriveGeneric
  - FlexibleInstances
  - LambdaCase
  - MultiParamTypeClasses
  - TupleSections